version: '1.0'
name: dtk-build-ccc-app-manager-20220829
displayName: dtk-build-ccc-app-manager
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
  pr:
    branches:
      prefix:
        - ''
variables:
  global:
    - WORK_FLOW_ENV_PKG_VERSION
stages:
  - name: stage-c9e7dc6d
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的DTK构建
        certificate: ''
        image: docker.jianmuhub.com/library/debian:buster
        command:
          - pwd
          - /bin/bash build-on-gitee.sh
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ../target
        caches: []
        notify: []
        strategy:
          retry: '0'
  - name: stage-421e5f07
    displayName: 上传
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        notify: []
        strategy:
          retry: '0'
